// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS_B7zLI7iQJiIe2drFQDvDaJgQ0sAS0c',
    appId: '1:768782412950:web:d56a90a6811c960d3366b7',
    messagingSenderId: '768782412950',
    projectId: 'capstone-efd73',
    authDomain: 'capstone-efd73.firebaseapp.com',
    databaseURL: 'https://capstone-efd73-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-efd73.appspot.com',
    measurementId: 'G-KGP9639SBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKuNIQPK2_4aWkeQvrpABif1c2a_PCQYw',
    appId: '1:768782412950:android:d1df1862d8a2ec873366b7',
    messagingSenderId: '768782412950',
    projectId: 'capstone-efd73',
    databaseURL: 'https://capstone-efd73-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-efd73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM9K_fZ_9wZyg_fNzy4sedyRFdkqVZouw',
    appId: '1:768782412950:ios:4d6b7790e61bf7bd3366b7',
    messagingSenderId: '768782412950',
    projectId: 'capstone-efd73',
    databaseURL: 'https://capstone-efd73-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-efd73.appspot.com',
    iosBundleId: 'com.example.icgm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM9K_fZ_9wZyg_fNzy4sedyRFdkqVZouw',
    appId: '1:768782412950:ios:c6587b23019137953366b7',
    messagingSenderId: '768782412950',
    projectId: 'capstone-efd73',
    databaseURL: 'https://capstone-efd73-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-efd73.appspot.com',
    iosBundleId: 'com.example.icgm.RunnerTests',
  );
}
